PackageIdentifier: AbdoslamB.InkDoc
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.17763.0
InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/AbdoslamB/inkdoc/releases/download/v1.0.0/inkdoc-setup.exe
    InstallerSha256: 2e28bb7947b7837d71cac788fff6cc7fadb6b48576448252c7e353de2d6287f3
    Scope: user
ManifestType: installer
ManifestVersion: 1.6.0
