PackageIdentifier: AbdoslamB.InkDoc
PackageVersion: 1.0.0
MinimumOSVersion: 10.0.17763.0
InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/AbdoslamB/inkdoc/releases/download/v1.0.0/inkdoc-setup.exe
    InstallerSha256: da1a89ddf7baea4b38d3cbdbe2adeee2c2fe068bcb41c487bd6c4ab6f7c9ebbd
    Scope: user
ManifestType: installer
ManifestVersion: 1.6.0
