"""Optional downloadable add-ons that extend an installed engine pack.

The first and only add-on is the Docling code/formula recognition model. It is
not bundled with the engine pack because it is 640 MB of weights that most users
will never exercise -- the pack is already a ~1 GB download -- so it is fetched
separately, and only by people who turn the feature on.

Why this is not part of EngineManager
-------------------------------------
EngineManager is single-pack by construction: `get_platform_pack_info`,
`is_platform_supported` and `is_pack_installed` all take an `engine_name` and
then hard-code `if engine_name != "docling": return None`. Generalising that
into a multi-artifact abstraction would mean reworking the code that performs
signature-adjacent integrity checks, to serve one optional feature. This module
instead reuses the primitives underneath -- `stream_download`,
`extract_archive_safely`, `check_disk_space`, `validate_download_url` -- which
are already hardened, and leaves the pack paths untouched.

Why the catalogue is a separate file
------------------------------------
`app/core/manifest.json` is regenerated by CI on every pack release:
`merge_manifest_fragments.py` builds it from four keys and writes it out, so
anything added alongside them is destroyed the next time a pack ships. Keeping
add-ons in `addons.json` also decouples the two release cadences, which is the
point of shipping the model separately in the first place.

Where the model has to live
---------------------------
Docling resolves models against a single `artifacts_path`, pinned by the pack
worker to `<pack>/models`, and raises rather than downloading when a model is
missing from it. There is no per-stage override, so the add-on has to install
into the pack's own models directory. Two consequences follow, and both are
deliberate: the add-on requires the pack to be installed first, and removing the
pack removes the add-on with it. Installed state is therefore always derived
from disk and never cached in settings, so the two can never disagree.
"""
from __future__ import annotations

import hashlib
import json
import logging
import shutil
import tempfile
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from app.core.download_utils import (
    DownloadError,
    SecurityError,
    check_disk_space,
    extract_archive_safely,
    is_safe_path,
    stream_download,
    validate_download_url,
)
from app.core.engine_manifest import is_valid_sha256

logger = logging.getLogger(__name__)

ADDONS_CATALOGUE_PATH = Path(__file__).resolve().parent / "addons.json"

# Written last, so a half-finished install is detectable by its absence rather
# than by trying to decide whether a directory of weights is complete.
_META_PREFIX = ".inkdoc-addon-"


class AddonError(Exception):
    """Raised for any add-on install, verify or removal failure."""


@dataclass
class AddonProgress:
    status: str = "idle"  # idle, downloading, verifying, extracting, installing, complete, error, cancelled
    bytes_downloaded: int = 0
    total_bytes: int = 0
    percent: float = 0.0
    error_message: str | None = None
    started_at: float = 0.0


@dataclass
class AddonInfo:
    name: str
    title: str
    description: str
    model_dir: str
    url: str
    sha256: str
    archive_format: str
    size_bytes: int
    uncompressed_size_bytes: int
    min_pack_version: str
    min_app_version: str
    sha256_files: dict[str, str] = field(default_factory=dict)


def version_tuple(value: str | None) -> tuple[int, ...]:
    """Parse a dotted version into comparable integers.

    Deliberately lenient: a version that cannot be read becomes (0,), which
    fails any "at least" comparison rather than accidentally satisfying one.
    """
    if not value or not isinstance(value, str):
        return (0,)
    parts: list[int] = []
    for chunk in value.strip().split("."):
        digits = "".join(c for c in chunk if c.isdigit())
        parts.append(int(digits) if digits else 0)
    return tuple(parts) or (0,)


def version_at_least(have: str | None, want: str | None) -> bool:
    """True when `have` is at least `want`. An absent requirement is satisfied."""
    if not want:
        return True
    return version_tuple(have) >= version_tuple(want)


class AddonManager:
    _instance: AddonManager | None = None
    _instance_lock = threading.Lock()

    def __init__(self, catalogue_path: Path | None = None) -> None:
        self._catalogue_path = catalogue_path or ADDONS_CATALOGUE_PATH
        self._catalogue: dict[str, AddonInfo] | None = None
        self._lock = threading.Lock()
        self._progress: dict[str, AddonProgress] = {}
        self._cancel_events: dict[str, threading.Event] = {}

    @classmethod
    def get_instance(cls) -> AddonManager:
        with cls._instance_lock:
            if cls._instance is None:
                cls._instance = cls()
            return cls._instance

    # ─── Catalogue ───────────────────────────────────────────────────────────

    def _load_catalogue(self) -> dict[str, AddonInfo]:
        if self._catalogue is not None:
            return self._catalogue
        catalogue: dict[str, AddonInfo] = {}
        try:
            raw = json.loads(self._catalogue_path.read_text(encoding="utf-8"))
            for name, entry in (raw.get("addons") or {}).items():
                catalogue[name] = AddonInfo(
                    name=name,
                    title=str(entry.get("title", name)),
                    description=str(entry.get("description", "")),
                    model_dir=str(entry.get("model_dir", "")),
                    url=str(entry.get("url", "")),
                    sha256=str(entry.get("sha256", "")).lower().strip(),
                    archive_format=str(entry.get("archive_format", "tar.gz")),
                    size_bytes=int(entry.get("size_bytes", 0) or 0),
                    uncompressed_size_bytes=int(entry.get("uncompressed_size_bytes", 0) or 0),
                    min_pack_version=str(entry.get("min_pack_version", "")),
                    min_app_version=str(entry.get("min_app_version", "")),
                    sha256_files=dict(entry.get("sha256_files") or {}),
                )
        except FileNotFoundError:
            logger.debug("No add-on catalogue at %s", self._catalogue_path)
        except Exception as exc:
            logger.warning("Could not read add-on catalogue: %s", exc)
        self._catalogue = catalogue
        return catalogue

    def get_addon(self, name: str) -> AddonInfo | None:
        return self._load_catalogue().get(name)

    def list_addon_names(self) -> list[str]:
        return sorted(self._load_catalogue())

    # ─── Locations ───────────────────────────────────────────────────────────

    def _models_dir(self) -> Path:
        from app.core.engine_manager import EngineManager

        return EngineManager.get_instance().get_engine_dir("docling") / "models"

    def _model_path(self, addon: AddonInfo) -> Path:
        return self._models_dir() / addon.model_dir

    def _meta_path(self, addon: AddonInfo) -> Path:
        return self._models_dir() / f"{_META_PREFIX}{addon.name}.json"

    # ─── Derived state ───────────────────────────────────────────────────────

    def is_installed(self, name: str) -> bool:
        """Installed means the weights are present *and* the install finished.

        The metadata file is written last, so its absence marks an interrupted
        install even when the model directory looks plausible.
        """
        addon = self.get_addon(name)
        if not addon or not addon.model_dir:
            return False
        try:
            return self._model_path(addon).is_dir() and self._meta_path(addon).is_file()
        except Exception:
            return False

    def get_status(self, name: str) -> dict[str, Any]:
        """Everything the UI needs to choose between its four states."""
        from app._version import get_version
        from app.core.engine_manager import EngineManager

        addon = self.get_addon(name)
        if not addon:
            return {"name": name, "available": False, "reason": "Unknown add-on"}

        mgr = EngineManager.get_instance()
        pack_installed = False
        pack_version = None
        try:
            pack_installed = mgr.is_pack_installed("docling")
            meta = mgr.get_engine_dir("docling") / "pack_meta.json"
            if meta.is_file():
                pack_version = json.loads(meta.read_text(encoding="utf-8")).get("pack_version")
        except Exception as exc:
            logger.debug("Could not read pack state: %s", exc)

        installed = self.is_installed(name)
        pack_ok = version_at_least(pack_version, addon.min_pack_version)
        app_ok = version_at_least(get_version(), addon.min_app_version)

        if not pack_installed:
            reason = "Docling is not installed"
        elif not pack_ok:
            reason = f"Requires Docling pack {addon.min_pack_version} or newer"
        elif not app_ok:
            reason = f"Requires InkDoc {addon.min_app_version} or newer"
        else:
            reason = ""

        return {
            "name": addon.name,
            "title": addon.title,
            "description": addon.description,
            "installed": installed,
            "available": bool(addon.url) and bool(addon.sha256),
            "pack_installed": pack_installed,
            "pack_version": pack_version,
            "min_pack_version": addon.min_pack_version,
            "size_bytes": addon.size_bytes,
            # The toggles may only be enabled when this is true.
            "usable": installed and pack_installed and pack_ok and app_ok,
            "installable": (
                not installed and pack_installed and pack_ok and app_ok
                and bool(addon.url) and bool(addon.sha256)
            ),
            "reason": reason,
            "progress": self.get_progress(name),
        }

    def get_progress(self, name: str) -> dict[str, Any]:
        prog = self._progress.get(name, AddonProgress())
        return {
            "status": prog.status,
            "bytes_downloaded": prog.bytes_downloaded,
            "total_bytes": prog.total_bytes,
            "percent": round(prog.percent, 2),
            "error_message": prog.error_message,
        }

    def cancel(self, name: str) -> bool:
        event = self._cancel_events.get(name)
        if event:
            event.set()
            return True
        return False

    # ─── Install ─────────────────────────────────────────────────────────────

    def install(self, name: str) -> dict[str, Any]:
        addon = self.get_addon(name)
        if not addon:
            raise AddonError(f"Unknown add-on: '{name}'")

        with self._lock:
            current = self._progress.get(name)
            if current and current.status in ("downloading", "verifying", "extracting", "installing"):
                raise AddonError("An installation is already in progress.")
            progress = AddonProgress(status="downloading", started_at=time.time())
            self._progress[name] = progress
            cancel_event = threading.Event()
            self._cancel_events[name] = cancel_event

        status = self.get_status(name)
        if not status.get("installable"):
            progress.status = "error"
            progress.error_message = status.get("reason") or "Add-on cannot be installed"
            raise AddonError(progress.error_message)

        if not is_valid_sha256(addon.sha256):
            progress.status = "error"
            progress.error_message = "Add-on catalogue has an invalid SHA-256"
            raise SecurityError(progress.error_message)
        validate_download_url(addon.url)

        models_dir = self._models_dir()
        model_path = self._model_path(addon)
        # Everything lands beside the model directory so the final move is a
        # rename within one filesystem rather than a copy across devices.
        staging_dir = models_dir / f"{_META_PREFIX}{addon.name}.staging"
        tmp_dir = Path(tempfile.mkdtemp(prefix=f"inkdoc_addon_{addon.name}_"))
        archive = tmp_dir / f"{addon.name}.{addon.archive_format}"

        def on_progress(done: int, total: int) -> None:
            progress.bytes_downloaded = done
            progress.total_bytes = total or addon.size_bytes
            if progress.total_bytes:
                progress.percent = (done / progress.total_bytes) * 100.0

        try:
            check_disk_space(
                models_dir,
                addon.size_bytes,
                uncompressed_bytes=addon.uncompressed_size_bytes,
            )

            calc = stream_download(
                url=addon.url,
                destination_path=archive,
                expected_size=addon.size_bytes or None,
                uncompressed_size=addon.uncompressed_size_bytes,
                cancel_event=cancel_event,
                progress_callback=on_progress,
                user_agent="InkDoc-AddonManager/1.0",
            )

            progress.status = "verifying"
            if calc.lower() != addon.sha256:
                raise SecurityError(
                    f"Checksum mismatch for add-on '{addon.name}': "
                    f"expected {addon.sha256}, got {calc.lower()}."
                )

            progress.status = "extracting"
            if staging_dir.exists():
                shutil.rmtree(staging_dir, ignore_errors=True)
            extract_archive_safely(archive, staging_dir)

            # The archive is expected to contain the model directory itself, so
            # a nested single directory is unwrapped rather than double-nested.
            staged_model = staging_dir / addon.model_dir
            if not staged_model.is_dir():
                entries = [p for p in staging_dir.iterdir()]
                if len(entries) == 1 and entries[0].is_dir():
                    staged_model = entries[0]
            if not staged_model.is_dir():
                raise AddonError(
                    f"Add-on archive does not contain '{addon.model_dir}'."
                )
            if not is_safe_path(staging_dir, staged_model):
                raise SecurityError("Add-on archive resolved outside its staging directory.")

            self._verify_tree(addon, staged_model)

            progress.status = "installing"
            if cancel_event.is_set():
                raise AddonError("Installation cancelled by user.")
            if model_path.exists():
                shutil.rmtree(model_path, ignore_errors=True)
            model_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(staged_model), str(model_path))

            # Last, so an interrupted install never looks complete.
            self._meta_path(addon).write_text(
                json.dumps(
                    {
                        "addon": addon.name,
                        "model_dir": addon.model_dir,
                        "sha256": addon.sha256,
                        "min_pack_version": addon.min_pack_version,
                        "installed_at": time.time(),
                    },
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            progress.status = "complete"
            progress.percent = 100.0
            logger.info("Add-on '%s' installed to %s", addon.name, model_path)
            return {"status": "installed", "addon": addon.name, "path": str(model_path)}

        except Exception as exc:
            progress.status = "cancelled" if cancel_event.is_set() else "error"
            progress.error_message = str(exc)
            # A partial model directory would otherwise be indistinguishable
            # from a good one to anything that only checks for its presence.
            shutil.rmtree(staging_dir, ignore_errors=True)
            if not self._meta_path(addon).is_file():
                shutil.rmtree(model_path, ignore_errors=True)
            logger.error("Add-on '%s' install failed: %s", addon.name, exc)
            raise
        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)
            shutil.rmtree(staging_dir, ignore_errors=True)
            self._cancel_events.pop(name, None)

    # ─── Verify and remove ───────────────────────────────────────────────────

    def _verify_tree(self, addon: AddonInfo, root: Path) -> None:
        """Hash every file the catalogue names. Fails closed on a bad entry."""
        if not addon.sha256_files:
            return
        for rel_path, expected in addon.sha256_files.items():
            exp = (expected or "").lower().strip()
            if not is_valid_sha256(exp):
                raise SecurityError(
                    f"Add-on catalogue has an invalid SHA-256 for '{rel_path}'."
                )
            target = root / rel_path
            if not is_safe_path(root, target):
                raise SecurityError(f"Add-on file path escapes its directory: '{rel_path}'.")
            if not target.is_file():
                raise SecurityError(f"Add-on is missing required file: '{rel_path}'.")
            actual = hashlib.sha256(target.read_bytes()).hexdigest().lower()
            if actual != exp:
                raise SecurityError(
                    f"Add-on file integrity check failed for '{rel_path}'."
                )

    def verify(self, name: str) -> dict[str, Any]:
        addon = self.get_addon(name)
        if not addon:
            return {"valid": False, "reason": f"Unknown add-on: '{name}'"}
        if not self.is_installed(name):
            return {"valid": False, "reason": "Add-on is not installed"}
        try:
            self._verify_tree(addon, self._model_path(addon))
        except Exception as exc:
            return {"valid": False, "reason": str(exc)}
        return {"valid": True, "addon": addon.name, "path": str(self._model_path(addon))}

    def remove(self, name: str) -> dict[str, Any]:
        addon = self.get_addon(name)
        if not addon:
            raise AddonError(f"Unknown add-on: '{name}'")
        # Metadata first: if the directory removal is interrupted, the add-on
        # still reads as not installed rather than as a usable half-install.
        meta = self._meta_path(addon)
        try:
            if meta.is_file():
                meta.unlink()
        except OSError as exc:
            raise AddonError(f"Could not remove add-on metadata: {exc}") from exc
        shutil.rmtree(self._model_path(addon), ignore_errors=True)
        self._progress.pop(name, None)
        logger.info("Add-on '%s' removed", addon.name)
        return {"status": "removed", "addon": addon.name}


__all__ = [
    "AddonError",
    "AddonInfo",
    "AddonManager",
    "AddonProgress",
    "DownloadError",
    "version_at_least",
    "version_tuple",
]
